Programm/ReklaToolPrototyp-master/ReklaTool/Controllers/PagesController.cs
using System.Net;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ReklaTool.Controllers
{
    public class PagesController : Controller
    {
        //[Authorize]
        public IActionResult Vorgang()
        {
            return View();
        }
        public IActionResult Error()
        {
            return View();
        }
    }
}

Programm/ReklaToolPrototyp-master/ReklaTool/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ReklaTool</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
	<link href="https://cdn.kendostatic.com/2022.2.621/styles/kendo.bootstrap-main.min.css" rel="stylesheet" type="text/css" />
	<script src="https://cdn.kendostatic.com/2022.2.621/js/jquery.min.js"></script>
	<script src="https://cdn.kendostatic.com/2022.2.621/js/jszip.min.js"></script>
	<script src="https://cdn.kendostatic.com/2022.2.621/js/kendo.all.min.js"></script>
    <script src="https://cdn.kendostatic.com/2022.2.621/js/kendo.aspnetmvc.min.js"></script>
    <style>
        .k-column-title {
            height: auto;
        }
        .k-column-title {
            white-space:pre-line;
        }
    </style>
</head>
<body width="100%" class="k-content">

@*<nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid d-flex justify-content-between p-0">
        <a class="navbar-brand d-flex align-items-center" asp-controller="Pages" asp-action="Vorgang">ReklaTool</a>
        <button id="configure" class="k-rpanel-toggle k-button k-button-md k-button-rectangle k-button-solid-primary btn-toggle">
            <span class="k-icon k-i-menu"></span>
        </button>
    </div>
</nav>*@
<nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" style="text-align:center" asp-controller="Pages" asp-action="Vorgang">ReklaTool</a>
</nav>

<main>
    <div class="container-fluid">
        @RenderBody()
    </div>
</main>

<footer class="footer text-center d-flex align-items-center">
    <div class="container-fluid">
        <p class="text-muted">
            Copyright © @DateTime.Now.Year Progress Software Corporation and/or its subsidiaries or affiliates. All rights reserved.
        </p>
    </div>
</footer>

<environment names="Development">
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
</environment>
<environment names="Staging,Production">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            asp-fallback-src="~/lib/bootstrap/js/bootstrap.bundle.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"></script>
</environment>

@RenderSection("scripts", required: false)
</body>
</html>